### ISSUE TITLE
how can i use this?

### ISSUE THREAD

**Issue by qqqqpppp** [baselsayeh/custombackdoorlshserver#1]
linux:$ ./Android.mk NDK_PROJECT_PATH=./ NDK_LIBS_OUT=./bin NDK_OUT=. TARGET_ARCH_ABI=arm64-v8a TARGET_PLATFORM=android-23

**Comment by baselsayeh** [comment]
read this: https://github.com/baselsayeh/custombackdoorlshserver/blob/master/README.md

get ndk from here: https://developer.android.com/ndk/downloads/index.html

((note:if you cant compile then copy libselinux from your device to lib folder in your platform (and arch) folder))

if you have another questions, feel free to ask
